// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ChinaHeatmap: typeof import('./components/Common/ChinaHeatmap/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WordCloud: typeof import('./components/Common/WordCloud/index.vue')['default']
    WorldHeatmap: typeof import('./components/Common/WorldHeatmap/index.vue')['default']
  }
}

export { }
